spring:
  cloud:
    # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
        service: ${spring.application.name} # 注册到Nacos的服务名，不配置默认为应用名
        username: nacos  # 如果开启Nacos权限认证nacos.core.auth.enabled=true, 需要配置上账号密码
        password: nacos
        namespace: edd2dc17-d38d-417e-aac8-dbe44737f807 # Nacos dev 命名空间